var RemoteTrainer;
(function (RemoteTrainer) {
    var Program = (function () {
        function Program() {
            this.index = 0;
        }
        Object.defineProperty(Program, "instance", {
            get: function () {
                if (!Program.s_instance)
                    Program.s_instance = new Program();
                return Program.s_instance;
            },
            enumerable: true,
            configurable: true
        });
        Program.prototype.runApplication = function () {
            this._createDemoData();
            this.set = ko.observable(new RemoteTrainer.Data.Set(this.m_setTemplates[0]));
            this.set().series()[0].uiStatus(RemoteTrainer.Data.SerieStatus.Ready);
            //serie.uiStartedOn(new Date(Date.now()));
            //serie.uiFinishedOn(new Date(Date.now()));
            ko.applyBindings(this);
        };
        Program.prototype._createDemoData = function () {
            this.m_categories = [new RemoteTrainer.Data.Category("Brucho", "#eeece1", "#ddd9c4"),
                new RemoteTrainer.Data.Category("Cardio", "blue", "navy"),
                new RemoteTrainer.Data.Category("Prsia", "#dce6f1", "#b8cce4"),
                new RemoteTrainer.Data.Category("Nohy", "#dce6f1", "#b8cce4"),
                new RemoteTrainer.Data.Category("Ramena", "#dce6f1", "#b8cce4")];
            this.m_exercises = [];
            var exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[0];
            exercise.name = "Skracovacky";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[0];
            exercise.name = "Pritahy k brade na lavicke";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.none;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[0];
            exercise.name = "Skracovacky na stroji";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[0];
            exercise.name = "Vytacanie do boku";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[2];
            exercise.name = "Tlaky v sede na stroji";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[2];
            exercise.name = "Bench sikma dole";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[3];
            exercise.name = "Drepy v raily";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[3];
            exercise.name = "Kracanie so zatazou";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[3];
            exercise.name = "Predkopavanie";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[3];
            exercise.name = "Zakopavanie";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[3];
            exercise.name = "Lytka sikma";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[4];
            exercise.name = "Upazovanie s cinkami";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[4];
            exercise.name = "Predpazovanie s cinkami";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[4];
            exercise.name = "Tlak na stroji";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[4];
            exercise.name = "Trapezy";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.kg;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.reps;
            this.m_exercises.push(exercise);
            exercise = new RemoteTrainer.Data.Exercise();
            exercise = new RemoteTrainer.Data.Exercise();
            exercise.category = this.m_categories[0];
            exercise.name = "Plank";
            exercise.uoa = RemoteTrainer.Data.UnitOfAmount.none;
            exercise.uor = RemoteTrainer.Data.UnitOfRepetitions.sec;
            this.m_exercises.push(exercise);
            this.m_setTemplates = [];
            var set = new RemoteTrainer.Data.SetTemplate();
            set.order = 1;
            set.serieTemplates = [];
            var serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[6], 10, 50);
            var serie2 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[1], 30);
            set.addSerie(serie1);
            set.addSerie(serie2);
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 2;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[7], 20, 10);
            set.addSerie(serie1);
            set.addSerie(serie1.clone());
            set.addSerie(serie1.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 3;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[8], 10, 50);
            serie2 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[2], 15, 70);
            set.addSerie(serie1);
            set.addSerie(serie2);
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 4;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[9], 15, 35);
            set.addSerie(serie1);
            set.addSerie(serie1.clone());
            set.addSerie(serie1.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 5;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[10], 10, 120);
            serie2 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[3], 10, 15);
            set.addSerie(serie1);
            set.addSerie(serie2);
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 6;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[11], 10, 8);
            set.addSerie(serie1);
            serie2 = serie1.clone();
            serie2.reps = 8;
            set.addSerie(serie2);
            serie2 = serie1.clone();
            serie2.reps = 6;
            set.addSerie(serie2);
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 7;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[12], 10, 10);
            set.addSerie(serie1);
            set.addSerie(serie1.clone());
            set.addSerie(serie1.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 8;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[13], 10, 35);
            set.addSerie(serie1);
            set.addSerie(serie1.clone());
            set.addSerie(serie1.clone());
            this.m_setTemplates.push(set);
            set = new RemoteTrainer.Data.SetTemplate();
            set.order = 9;
            set.serieTemplates = [];
            serie1 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[14], 10, 20);
            serie2 = new RemoteTrainer.Data.SerieTemplate(this.m_exercises[15], 75);
            set.addSerie(serie1);
            set.addSerie(serie2);
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            set.addSerie(serie1.clone());
            set.addSerie(serie2.clone());
            this.m_setTemplates.push(set);
        };
        return Program;
    }());
    RemoteTrainer.Program = Program;
})(RemoteTrainer || (RemoteTrainer = {}));
//# sourceMappingURL=app.js.map